### ISSUE TITLE
Prey Doesnt works

### ISSUE THREAD

**Issue by Talixme** [hurrican6/PS4_Cheater#1]
Some games like "Prey" doesnt even start the game.

Thanks for the app works great.

**Comment by hurrican6** [comment]
4.05 or 4.55?

**Comment by Talixme** [comment]
Sorry for the info.
Ps4 Firmware: 4.55
EP1003-CUSA06560_00-PREYPS4FULLGAME1-A0100-V0100 EUR Version 1.00
EP1003-CUSA06560_00-PREYPS4FULLGAME1-A0100-V0104 EUR Version 1.04
UP1003-CUSA04493_00-PREYPS4FULLGAME1-A0100-V0100 USA Version 1.00

None of then boots.

Thanks

**Comment by hurrican6** [comment]
Does PS4 Cheater 1.2 with 4.55 patch have this issue, too?
Actually, I have not updated my firmware to 4.55, it's hard to reproduce for me.
Not all games have this issue on 4.55 with PS4 Cheater 1.2.2, right?
Thanks!

**Comment by Talixme** [comment]
"Does PS4 Cheater 1.2 with 4.55 patch have this issue, too?"
Yes, all versions
Not all games have this issue on 4.55 with PS4 Cheater 1.2.2, right?
No, as i know this game, and some games with "updates"

Thanks

**Comment by hurrican6** [comment]
This should be JKPatch's issue.

**Comment by Talixme** [comment]
It is. I thought that you can fix Jkpatch too.

Thanks and sorry.

**Comment by hurrican6** [comment]
Thanks for your support!
