### ISSUE TITLE
Librpc error scanning all section

### ISSUE THREAD

**Issue by Pretinaverse** [hurrican6/PS4_Cheater#10]
Like the title say, almost all the time i try to make a full scan of eboot.bin (selecting all the sections) i get an librpc error. I don't know if this is a problem with jkpatch or the tool itself. But either way, can you make it so the tool "skip" the error? Like trying ti reconnect and continuing the search in the section who gives the error, and if it not possible to scan that section, then jump to the next one.

Everytime the error appear, no resukts are shown. The search automatically cancel itself. I wonder if you can fix this so the results are not lost everytime the error pop up.

**Comment by Talixme** [comment]
Have you try the 1.3.1 version?
I dont have that error anymore

**Comment by Pretinaverse** [comment]
Did a full scan of eboot.bin, playing Horizon Zero Dawn, and didn't get any error. I'm closing the issue.
