### ISSUE TITLE
Lock function is bugged.

### ISSUE THREAD

**Issue by Pretinaverse** [hurrican6/PS4_Cheater#11]
So, this happens to me, and it seems to others as well for what i could read in some comments in psxhax.

Sometimes, the locked values stop sending the values you lock to the ps4. This happened to me in Horizon Zero Dawn and in Star Ocean 5. 

- Unlocking and locking the values again did nothing. 

- The solution was: save the codes, refresh the processes and load the codes again. 

- Double click in the saved value and pressing the key enter seems to fix the problem as well. 

Only doing this, make ps4cheater to continuing sending the values to the ps4.

I think this problem only happens when you lock 2 or more values at the same time.

**Comment by hurrican6** [comment]
Still happen with 1.3.1? I thought I have fixed it...

**Comment by hurrican6** [comment]
I will check. Thanks!

**Comment by Pretinaverse** [comment]
Sorry. I forgot you updated ps4cheater. I will try 1.3.1  when i get home.
