### ISSUE TITLE
Offset and length were out of bounds for the array or count is greater

### ISSUE THREAD

**Issue by donmega** [hurrican6/PS4_Cheater#15]
Hi,

In Fallout4 i get the following error when doing a "next scan"

https://i.imgur.com/smYGAt9.png

I am running the newest version of PS4 Cheater. Can you help me out please?
Thx!

**Comment by Pretinaverse** [comment]
Another user (in the psxhax forum) is having the same problem with **sniper ghost warrior 3**

I think the full error is: _Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection._

**Comment by hurrican6** [comment]
Do you connect your PS4 with WIFI? 1.3.3 r3 may help you. Please try.

**Comment by donmega** [comment]
Seems to work great with the newest version! I am closing this issue. Thx a lot hurrican6!
A tip: Would it be possible to create an tutorial on how to find health? When i am trying to find health in several games it doesn't find the value (for example: Fallout 4 and Watch Dogs 2). Thx a lot :)
