### ISSUE TITLE
Saving pointer code

### ISSUE THREAD

**Issue by Talixme** [hurrican6/PS4_Cheater#16]
Hello,

When you save a pointer code the file its not correct, saves like this;

simple pointer|pointer|float|@36F29908_2_1908+298D7358|data|float|999999|1Souls|

Should be like;

simple pointer|pointer|float|@36F29908_2_1908+298D7358|data|float|999999|1|Souls|

Thanks for your hard work!!!

**Comment by Myoko** [comment]
how do i saving this pointer code? it so much biger
![sas](https://user-images.githubusercontent.com/3013386/38003333-b76e1742-3269-11e8-81ab-eec513e68770.jpg)

**Comment by vampirexx78** [comment]
Thank you Hurricane you are an amazing dev!!! I have same problem as Talix and even if i find 2 or 3 level pointer when i load it back into the game after restart console and coming in game again the loaded cheat say wrong section and it doesnt work please can you fix it? Thanx for this amazing and awresome tool my friend

**Comment by Talixme** [comment]
Fixed it.

Thanks
