### ISSUE TITLE
The window for new addresses grows without limit

### ISSUE THREAD

**Issue by Pretinaverse** [hurrican6/PS4_Cheater#17]
There is a problem with this window:

![mm01](https://user-images.githubusercontent.com/28994546/38069023-9588ac4c-32ea-11e8-8b22-7ef8a2204ebe.jpg)

If you add to many offsets, thw window grows without limit, until the buttons dissapear at the bottom of the screen:

![mm02](https://user-images.githubusercontent.com/28994546/38069042-b2193660-32ea-11e8-9692-5a988d00c3a2.jpg)

Maybe you can make that window movable, with a fixed size and a vertical scroll bar?

**Comment by hurrican6** [comment]
A little busy these days. I'll fix it someday. Thanks!

**Comment by Talixme** [comment]
Tested and now can move the window.
Just one thing, when you making a new code you, will be possible to move the "pointer finder" windows?? Some times is hard to copy the data to the "new code" window.
Thanks

**Comment by Pretinaverse** [comment]
Like talixme said, it would be great if we could manipulate the "pointer finder" window while adding a new code ;)

**Comment by hurrican6** [comment]
Sure. I'll try.
