### ISSUE TITLE
After messing with pointers, the float and hex search becomes buggy

### ISSUE THREAD

**Issue by Pretinaverse** [hurrican6/PS4_Cheater#18]
If i do several searches with the "Find Pointer" function or if i try to add a pointer manually, the float search in ps4cheater become bugged. Hex search too. 4 bytes seems to be working fine though. But i don't know about the rest fo the search types.

If i close ps4cheater and open it again, everything works perfectly again.

Here is a video so you can see the problem and how to reproduce it.

https://youtu.be/PNM6idWTLe0

**Comment by hurrican6** [comment]
Please try 1.4.1

**Comment by Pretinaverse** [comment]
Now is working fine. I'm closing the issue. Thanks!
