### ISSUE TITLE
1.4.1 Pointer Not Work

### ISSUE THREAD

**Issue by Myoko** [hurrican6/PS4_Cheater#20]
i try to find a pointer but when i reboot game address change
![ss](https://user-images.githubusercontent.com/3013386/38120439-6d1fdb6a-33fb-11e8-8d98-930e89ee876d.jpg)
![ssa](https://user-images.githubusercontent.com/3013386/38120441-70de9052-33fb-11e8-91bf-68a7ddebe4dc.jpg)

**Comment by Pretinaverse** [comment]
That's the way HZD works. The addresses change after every reboot. I don't know if it's possible to find a working pointer for this. Maybe you can try with a higher pointer level? Until now i tried with 13, but no luck.

**Comment by hurrican6** [comment]
Yes, Pretinaverse is right. You need find the root pointer, not all the pointers are right in the pointer finder list.
