### ISSUE TITLE
Sectioni wrong error?

### ISSUE THREAD

**Issue by Pretinaverse** [hurrican6/PS4_Cheater#21]
I may be doing something wrong, but I don't know what. For some reason the pointers I add don't work and instead give me the error: Sectioni wrong!

I was trying to find a health pointer in horizon zero dawn. One that continues to work even after rebooting the console. I did a first search and then turned off the ps4. I turned it back on and did a second search significantly reducing the results, but, for some reason, I can't add any of the pointers obtained.

The search I did was for level 15 pointers. And this is a video of me trying to add the pointers and the error i get.

https://youtu.be/Q3w74udDGf0

**Comment by vampirexx78** [comment]
Same issue here as i explained on hax, loaded cheat doesnt work, please fix Hurricane and thank you very much!!

**Comment by vampirexx78** [comment]
@Pretinaverse i think you re doing wrong you should input the last section3 address as your pointer, after that you add the difference address so for example first pointer is:

7EF6EC930
After that you add new offset

0 then 30 then 18 then 3C if it is the right one it should sum up and match your money / hp value. 

Is it right for me the problem is that you save it as cht file. Then restart ps4 go in game load cheat pointer and you always have wrong section issue

**Comment by mrimthatguy** [comment]
I also get same error not one person dose not get this error.

**Comment by Pretinaverse** [comment]
@vampirexx78 
that's how i did it. First the last and then the difference between addresses.
Maybe it's impossible to find pointers that keep working after a reboot of the console, even is there are results of pointers after rebooting the ps4.

I did a search first of level 15 pointers. I stopped the search when i has 20000 results. Shut down the console, turned it on again, find the new address for health and did a second search with the pointer finder. I obtained 151 results (a lot of them repeated). I though one of them should work after a reboot, but it seems they can't even be added.

I know how to add the pointers. If i don't reboot the console they work fine.

**Comment by vampirexx78** [comment]
Thats good buddy so you tried to insert all the possible pointers... i think maybe we are outlook we need that Hurrican insert a breakpoint function so we are hit by enemies , health go down and game pause it opens a windows on ps4cheater showing you what address in elf is writtin that code

**Comment by vampirexx78** [comment]
Hope this could be useful about pointers and how to find them in stack:

https://stackoverflow.com/questions/2926739/how-do-game-trainers-change-an-address-in-memory-thats-dynamic

**Comment by vampirexx78** [comment]
Hurricane is there a way to find the root pointer at least? Thanx

**Comment by hurrican6** [comment]
@Pretinaverse 1.4.2 can help you to find out the root pointer of HZD's life. Section wrong may be caused by that you find a wrong pointer. My English is not very well. Hope you can understand the usage in the release note.

**Comment by hurrican6** [comment]
@vampirexx78 Yes, there is. But not sure how much time you need. It is depending on the game's implementation.

**Comment by vampirexx78** [comment]
Thank you for the new release you re wonderful buddy thanx a lot i will test the tool we are on discord ps4cheater discussion, join with us if you want

**Comment by Pretinaverse** [comment]
I'm closing the issue. Thanks hurrican6, you are awesome xD
