### ISSUE TITLE
blank screen and auto restarting 

### ISSUE THREAD

**Issue by agungsetiawan23** [hurrican6/PS4_Cheater#4]
there is a bug on NIOH CUSA07123, when i try to using ps4 cheater 1.3.0
before in the game menu my ps4 just auto restarting, maybe the jkpatch is the problem.
hope u fix it soon, thank you.

**Comment by 3096** [comment]
Ay PS4 cheater is just a client for jkpatch, STOP posting these stuffs here. There isn't even a 1.3 yet

**Comment by agungsetiawan23** [comment]
ah sorry, wrong section

**Comment by 3096** [comment]
You know you can delete this right?

**Comment by agungsetiawan23** [comment]
there is a 1.3.0, u can find it on bin/x64/
