### ISSUE TITLE
can you integrate Hen into the payload please?

### ISSUE THREAD

**Issue by vampirexx78** [hurrican6/PS4_Cheater#7]
Hi can you please add hen inside the payload because sometimes the payload cannot attach ps4 on 4.55 and i guess after sending hen payload. Thanx for your hard work this tool is awesome!!!!!!!! Hope you can also enlarge the amount of unknow float values on first scan if possible and alo breakpoint the address to see in elf what routine is writing, like cheat engine for pc.

Thanx you so much Hurricane you a re a great dev!

**Comment by Talixme** [comment]
Already has it.Anyway That resquest is for Jkpatch :)

**Comment by vampirexx78** [comment]
Thanx Talix i dont have debug settings after sending the payload on 4.55

**Comment by Talixme** [comment]
I have 4.55 to, and after send the payload with the app, i have debug setting enabled. So check other things because this works fine :)

**Comment by vampirexx78** [comment]
Can you send me your payload please? Im using al azif 4.0.1 and also copy the payload inside this tool

**Comment by vampirexx78** [comment]
I close the issue then and hope Hurricane can help with the request on top. Thank you
