### ISSUE TITLE
Range of memory selection

### ISSUE THREAD

**Issue by Pretinaverse** [hurrican6/PS4_Cheater#8]
Can you add a function to be able to select more than one memory range at a time? It is exhausting to have to select them one at a time, especially when there are dozens of them.

I mean something like this (I used photoshop for the picture):

![sin titulo-1](https://user-images.githubusercontent.com/28994546/37551637-3859b5be-2982-11e8-9b4a-a7753d4de7a4.jpg)

By the way, I remember that in version 1.1 of the program, ps4cheater automatically selected the memory ranges in which it might be possible to find game values. Why did you delete that function?

**Comment by hurrican6** [comment]
Thanks for your advice! But I think this should not be the final solution. I may speedup exact value searching 10x~100x on 1.4, then you can just select all the sections.

**Comment by Pretinaverse** [comment]
I do the search using an ethernet cable so, for me, the search was pretty fast already, haha. But with some games, if i select all sections, it disconnect in the middle of the search and give me some lib error. This error is most probably to happen with games who have a lot of sections. And with that, i mean, dozens of sections. I think Skyrim was one of those games with dozens and dozens of small sections with a lenght of 16 or 32 KB.
